from typing import Protocol, Dict, Any

class AttachmentHost(Protocol):
    def write_digital_output(self, channel: int, value: bool, **kwargs) -> None: ...

    def manage_gripper(self, rotation: int, gripper: int, **kwargs) -> None: ...

    def manage_vacuum(self, rotation: int, power_supply: bool, **kwargs) -> None: ...

    def get_status(self) -> Dict[str, Any]: ... 